---

plugins:
  - jest
  - babel

env:
  node: true
  jest/globals: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  global-require: 0
  no-alert: 0
  no-param-reassign: 0
